# Generated by Django 5.2.7 on 2025-10-30 14:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polizas', '0003_cotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaAseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(help_text='Número de cuenta bancaria', max_length=50)),
                ('banco', models.CharField(max_length=100)),
                ('tipo_cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('rif', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_contacto', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('metodo', models.CharField(blank=True, help_text='Ej: Transferencia, Pago móvil, etc.', max_length=50, null=True)),
                ('referencia', models.CharField(blank=True, help_text='Número de referencia del pago', max_length=100, null=True)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('pagado', models.BooleanField(default=False)),
                ('verificado', models.BooleanField(default=False, help_text='Marcar cuando un administrador confirme el pago')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('aseguradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='pagos.empresaaseguradora')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='polizas.poliza')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
