# Generated by Django 5.2.7 on 2025-10-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('agent', 'Agente'), ('client', 'Cliente'), ('finance', 'Finanzas')], default='client', max_length=20),
        ),
    ]
