# Generated by Django 5.2.7 on 2025-11-19 15:53

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfil_cedula_perfil_direccion_perfil_documento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='documento_id',
            field=models.FileField(blank=True, null=True, upload_to=usuarios.models.renombrar_documento),
        ),
    ]
