# Generated by Django 5.2.7 on 2025-11-19 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaccion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Interacción', 'verbose_name_plural': 'Interacciones'},
        ),
        migrations.RenameField(
            model_name='interaccion',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='interaccion',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacciones_agente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('RE', 'Resuelta'), ('CA', 'Cancelada')], default='PE', max_length=2),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='tipo',
            field=models.CharField(choices=[('LL', 'Llamada'), ('EM', 'Email'), ('CH', 'Chat')], default='EM', max_length=2),
        ),
        migrations.AlterField(
            model_name='interaccion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones_cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
