# Generated by Django 5.2.7 on 2025-10-22 19:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoPoliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('SALUD', 'Salud'), ('AUTO', 'Automóvil'), ('HCM_INDIVIDUAL', 'H.C.M Individual'), ('ACCIDENTES_PERSONALES', 'Accidentes Personales'), ('VIDA_INDIVIDUAL', 'Vida Individual'), ('HOGAR', 'Hogar'), ('FUNERARIO', 'Servicio Funerario'), ('RESP_PATRONAL', 'Responsabilidad Civil Patronal'), ('RESP_EMPRESARIAL', 'Responsabilidad Civil Empresarial'), ('CANCER', 'Patología de Cáncer'), ('CASCO_NAVES', 'Casco Naves (Lanchas)'), ('RESP_EMBARCACION', 'Responsabilidad Civil Embarcación'), ('FIDELIDAD', 'Fidelidad 3D'), ('RESP_GENERAL', 'Responsabilidad Civil General'), ('INCENDIO', 'Incendio'), ('RESP_VEHICULOS', 'Responsabilidad Civil Vehículos'), ('COMBINADO_RESIDENCIA', 'Combinado de Residencia'), ('COBERTURA_AMPLIA', 'Cobertura Amplia'), ('OCUPANTES_VEHICULOS', 'Ocupantes de Vehículos'), ('TODO_RIESGO_INDUSTRIAL', 'Todo Riesgo Industrial'), ('RESP_PROFESIONAL', 'Responsabilidad Civil Profesional')], max_length=50)),
                ('cobertura', models.JSONField(blank=True, default=dict)),
                ('prima_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='poliza',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='poliza',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='poliza',
            name='precio',
        ),
        migrations.AddField(
            model_name='poliza',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poliza',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poliza',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to='polizas/documentos/'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20),
        ),
        migrations.AddField(
            model_name='poliza',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='poliza',
            name='poliza_numero',
            field=models.CharField(default='P-DEFAULT', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='prima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poliza',
            name='sum_insured',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='tipo',
            field=models.CharField(choices=[('SALUD', 'Salud'), ('AUTO', 'Automóvil'), ('HCM_INDIVIDUAL', 'H.C.M Individual'), ('ACCIDENTES_PERSONALES', 'Accidentes Personales'), ('VIDA_INDIVIDUAL', 'Vida Individual'), ('HOGAR', 'Hogar'), ('FUNERARIO', 'Servicio Funerario'), ('RESP_PATRONAL', 'Responsabilidad Civil Patronal'), ('RESP_EMPRESARIAL', 'Responsabilidad Civil Empresarial'), ('CANCER', 'Patología de Cáncer'), ('CASCO_NAVES', 'Casco Naves (Lanchas)'), ('RESP_EMBARCACION', 'Responsabilidad Civil Embarcación'), ('FIDELIDAD', 'Fidelidad 3D'), ('RESP_GENERAL', 'Responsabilidad Civil General'), ('INCENDIO', 'Incendio'), ('RESP_VEHICULOS', 'Responsabilidad Civil Vehículos'), ('COMBINADO_RESIDENCIA', 'Combinado de Residencia'), ('COBERTURA_AMPLIA', 'Cobertura Amplia'), ('OCUPANTES_VEHICULOS', 'Ocupantes de Vehículos'), ('TODO_RIESGO_INDUSTRIAL', 'Todo Riesgo Industrial'), ('RESP_PROFESIONAL', 'Responsabilidad Civil Profesional')], max_length=50),
        ),
    ]
