# Generated by Django 5.2.7 on 2025-10-30 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
        ('polizas', '0003_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='aseguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas', to='pagos.empresaaseguradora'),
        ),
    ]
