# Generated by Django 5.2.7 on 2025-11-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0004_poliza_aseguradora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('PEND_VERIF', 'Pago pendiente de verificación'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=50),
        ),
    ]
