# Generated by Django 5.2.7 on 2025-11-28 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0005_alter_poliza_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='cobertura_extra',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='monto_estimado',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='producto',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='mail',
            field=models.EmailField(default='no_aplica@seguros.com', max_length=254),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='prima_estimada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='suma_asegurada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='telefono',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tipo_poliza',
            field=models.CharField(choices=[('SALUD', 'Salud'), ('AUTO', 'Automóvil'), ('HCM_INDIVIDUAL', 'H.C.M Individual'), ('ACCIDENTES_PERSONALES', 'Accidentes Personales'), ('VIDA_INDIVIDUAL', 'Vida Individual'), ('HOGAR', 'Hogar'), ('FUNERARIO', 'Servicio Funerario'), ('RESP_PATRONAL', 'Responsabilidad Civil Patronal'), ('RESP_EMPRESARIAL', 'Responsabilidad Civil Empresarial'), ('CANCER', 'Patología de Cáncer'), ('CASCO_NAVES', 'Casco Naves (Lanchas)'), ('RESP_EMBARCACION', 'Responsabilidad Civil Embarcación'), ('FIDELIDAD', 'Fidelidad 3D'), ('RESP_GENERAL', 'Responsabilidad Civil General'), ('INCENDIO', 'Incendio'), ('RESP_VEHICULOS', 'Responsabilidad Civil Vehículos'), ('COMBINADO_RESIDENCIA', 'Combinado de Residencia'), ('COBERTURA_AMPLIA', 'Cobertura Amplia'), ('OCUPANTES_VEHICULOS', 'Ocupantes de Vehículos'), ('TODO_RIESGO_INDUSTRIAL', 'Todo Riesgo Industrial'), ('RESP_PROFESIONAL', 'Responsabilidad Civil Profesional')], default='SALUD', max_length=50),
        ),
        migrations.AddField(
            model_name='productopoliza',
            name='cobertura_maxima',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productopoliza',
            name='deducible_dentro_usa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productopoliza',
            name='deducible_fuera_usa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productopoliza',
            name='detalles_extras',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productopoliza',
            name='etiqueta_destacada',
            field=models.CharField(choices=[('RECOMENDADO', 'Recomendado'), ('COMPLETO', 'Más Completo'), ('ALTERNATIVA', 'La Alternativa'), ('MAXIMA', 'Máxima'), ('BUENA_OPCION', 'Buena Opción'), ('-', 'Sin Etiqueta')], default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='productopoliza',
            name='nombre_aseguradora',
            field=models.CharField(default='Aseguradora X', max_length=100),
        ),
        migrations.AddField(
            model_name='productopoliza',
            name='prima_desde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productopoliza',
            name='prima_hasta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
