# Generated by Django 5.2.7 on 2025-12-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0006_remove_cotizacion_cobertura_extra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='mail',
        ),
    ]
