# Generated by Django 5.2.7 on 2025-12-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0007_remove_cotizacion_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
