# Generated by Django 5.2.7 on 2025-11-21 14:43

import django.db.models.deletion
import reclamos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reclamo',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='reclamo',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='codigo',
            field=models.CharField(blank=True, max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='reclamos/evidencias/', validators=[reclamos.models.validar_extension_evidencia, reclamos.models.validar_tamano_evidencia]),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='motivo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CERRADO', 'Cerrado')], default='PENDIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CERRADO', 'Cerrado')], max_length=20)),
                ('nota', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='reclamos.reclamo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
